FROM openjdk:8-jdk-alpine

LABEL maintainer = "Henrique Borsatto de Campos<henry_tuori@hotmail.com>"

ARG DEPENDENCY=target/dependency

COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","br.com.henry.selective.uol.customer.Application"]
