FROM openjdk:8-jdk-alpine

LABEL maintainer = "Henrique Borsatto de Campos<henry_tuori@hotmail.com>"

COPY app app

ENTRYPOINT ["java","-Dlogback.configurationFile=app/logback-spring.xml","-cp","app:app/lib/*","br.com.henry.selective.uol.customer.Application"]
